# Required parameters
params:
  OUTDIR: "upc_denv1_minperfect5/"
  PRIMERS: "input/primers_denv1.txt"
  CPU: 16
  SUBSAMPLE_TARGET: "no" #either max #genomes to keep or "no"
  SUBSAMPLE_OFFTARGET: 500
  PROBES: "yes"


# Provide custom genomes
custom:
  USER_TARGET:
  USER_OFFTARGET: 

download:
  DOWNLOAD_TARGET: "yes"
  DOWNLOAD_OFFTARGET: "yes"

# Genome download parameters
datasets:
  DB: "GenBank"
  TARGET_SP_TAXID: 11053
  OFFTARGET_SP_TAXID: 12637
  #TARGET_TAXID: ""
  #OFFTARGET_TAXID: ""
  DOMAIN: "viral"
  ASSEMBLY_LEVEL: "complete" #chromosome,complete,scaffold,contig
  USE_ASSEMBLY: "no"
  IS_FLU: "no"


# Insilico PCR parameters
ispcr:
  MAX_AMPLICON_SIZE: 500
  MIN_PERFECT: 5  # minimum size of perfect match at 3' end of primer (default 15)
  TILE_SIZE: 11   # the size of match that triggers an alignment (default 11)
  STEP_SIZE: 5    # spacing between tiles (default 5)
  MIN_GOOD: 15    # minimum size where there must be 2 matches for each mismatch (default 15)


# Phylogeny parameters
phylo:
  DEREP: "yes"




