# Run parameters
OUTDIR: "upc_flu/"
CPU: 4
REF: "ref_flu.fasta"

# Insilico PCR parameters
PRIMERS: "primers_flu.txt"
MAX_AMPLICON_SIZE: 2000
MIN_PERFECT: 5
TILE_SIZE: 8

# Genome download parameters
DOWNLOAD_TARGET: "yes"
DOWNLOAD_OFFTARGET: "yes"
DB: "refseq"
TARGET_SP_TAXID: "2955291"
OFFTARGET_SP_TAXID: "2955465"
DOMAIN: "viral"
ASSEMBLY_LEVEL: "complete"

# Phylogeny parameters
DEREP: "yes"

# User-provided genomes (comment out if not providing)
#USER_TARGET: "target_user"
#USER_OFFTARGET: "offtarget_user"