# Run parameters
OUTDIR: "upc_jev/"
CPU: 4
REF: "ref.fasta"

# Insilico PCR parameters
PRIMERS: "primers_input.txt"
MAX_AMPLICON_SIZE: 2000
MIN_PERFECT: 5
TILE_SIZE: 8

# Genome download parameters
DOWNLOAD_TARGET: "yes"
DOWNLOAD_OFFTARGET: "no"
DB: "GenBank"  #RefSeq or GenBank
TARGET_SP_TAXID: "3048158"
OFFTARGET_SP_TAXID: "3052464"
#TARGET_TAXID: "11072"
#OFFTARGET_TAXID: ""
DOMAIN: "viral"
ASSEMBLY_LEVEL: "complete" #chromosome,complete,scaffold,contig
USE_ASSEMBLY: "no"

# Phylogeny parameters
DEREP: "yes"

# User-provided genomes (comment out if not providing)
#USER_TARGET: "target_user"
USER_OFFTARGET: "offtarget_user"
